### ISSUE TITLE
default attribute typecheck failure on constraint types using plugins

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta#1725]
The following model fails:
```
entity Test:
    std::date d = "2020-01-22"
end
```
with
```
AttributeError: 'validate_type' object has no attribute 'argtypes'
```
at
```
src/inmanta/plugins.py:313
```

This is due the the scheduling of default attributes type checks introduced in #1718
